parameters:
#    lantern_menu.example.class: Lantern\MenuBundle\Example

services:
#    lantern_menu.example:
#        class: %lantern_menu.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
