LanternAppBundle_index:
    pattern:  /
    defaults: { _controller: LanternAppBundle:Default:index }

LanternAppBundle_install:
    resource: "@LanternAppBundle/Resources/config/routing/install.yml"
    prefix:   /install

ajax:
    pattern:  /ajax
    defaults: { _controller: LanternAppBundle:Ajax:ajax }

ajax_test:
    pattern:  /ajaxtest
    defaults: { _controller: LanternAppBundle:Default:ajaxTest }