<?php

namespace Lantern\MediaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CollectionTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollectionTagRepository extends EntityRepository
{
}
