<?php

namespace Lantern\MediaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MediaTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaTagRepository extends EntityRepository
{
}
