Lantern\MenuBundle\Entity\Menu:
    type:            entity
    table:           lantern_menu
    repositoryClass: Lantern\MenuBundle\Entity\MenuRepository
    id:
        id:
            id:       true
            type:     integer
            unsigned: false
            nullable: false
            generator:
                strategy: AUTO
            sequenceGenerator:
                sequenceName:   lantern_menu_id_seq
                initialValue:   1
                allocationSize: 1
    fields:
        title:
            column:   title
            type:     string
            length:   64
            nullable: false
        description:
            column:   description
            type:     text
            nullable: true
            unique:   false
    uniqueConstraints:
        lantern_menu_unique_idx:
            columns: [ title ]
    lifecycleCallbacks: {  }
