<?php

namespace Lantern\AuthBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AuthRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthRoleRepository extends EntityRepository
{
}
