<?php

namespace Lantern\AuthBundle\Entity;

use Symfony\Component\Security\Core\Role\RoleHierarchy;

/**
 * Role Manager
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleManager
{
    protected $roleHeirarchy;

    public function __construct(RoleHierarchy $roleHierarchy)
    {  
        $this->roleHierarchy = $roleHierarchy; // serviceId = security.role_hierarchy
    }

    public function hasRole($roles, $targetRole)
    {
        $reachableRoles = $this->roleHierarchy->getReachableRoles($roles);
        
        foreach($reachableRoles as $role)
        {
            if ($role->getRole() == $targetRole) return true;
        }
        
        return false;
    }
}
