lantern_user:
    resource: "@LanternUserBundle/Resources/config/routing.yml"
    prefix:   /

lantern_menu:
    resource: "@LanternMenuBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path:   /login
    defaults:  { _controller: LanternAuthBundle:Security:login }

login_check:
    path:   /login_check
    requirements: { _method: POST }

logout:
    path:   /logout

account_register:
    path:     /register
    defaults: { _controller: LanternAuthBundle:Account:register }

account_create:
    path:     /register/create
    defaults: { _controller: LanternAuthBundle:Account:create }

# Lantern Application Core bundle
LanternAppBundle:
    resource: "@LanternAppBundle/Resources/config/routing.yml"
    prefix:   /

# Lantern Dependency Bundles
LanternAuthBundle:
    resource: "@LanternAuthBundle/Resources/config/routing.yml"
    prefix:   /auth

LanternFileMgrBundle:
    resource: "@LanternFileMgrBundle/Resources/config/routing.yml"
    prefix:   /filemgr

LanternFormBundle:
    resource: "@LanternFormBundle/Resources/config/routing.yml"
    prefix:   /form

LanternIntlBundle:
    resource: "@LanternIntlBundle/Resources/config/routing.yml"
    prefix:   /intl

LanternMediaParserBundle:
    resource: "@LanternMediaParserBundle/Resources/config/routing.yml"
    prefix:   /mediaparse

LanternTwigExtBundle:
    resource: "@LanternTwigExtBundle/Resources/config/routing.yml"
    prefix:   /twigext

# Lantern Theme Bundles
LanternThemeModernThemeBundle:
    resource: "@LanternThemeModernThemeBundle/Resources/config/routing.yml"
    prefix:   /moderntheme
