security:
    encoders:
        Lantern\AuthBundle\Entity\AuthUser:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity:
                class:    Lantern\AuthBundle\Entity\AuthUser
                property: username

    firewalls:
        dev:
            pattern:    ^/(_profiler|_wdt|css|js|font|ico|img|bundles)
            security:   false
        main:
            pattern:    ^/
            provider:   main
            http_basic: true
            anonymous:  true
            logout:
                path:   logout
                target: /
            form_login: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/create, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }