security:
    encoders:
        Lantern\AuthBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity:
                class:    Lantern\AuthBundle\Entity\User
                property: username

    firewalls:
        dev:
            pattern:    ^/(_profiler|_wdt|css|js|font|ico|img|bundles)
            security:   false
        main:
            remember_me:
                key:      "%secret_dos%"
                lifetime: 31536000
                path:     /
                domain:   ~
            switch_user: { role: ROLE_ALLOWED_TO_SWITCH, parameter: _switch_user }
            pattern:    ^/
            provider:   main
            http_basic: true
            anonymous:  true
            logout:
                path:   logout
                target: /
            form_login: ~

    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/reset, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/create, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/install, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }