Lantern\FileMgrBundle\Entity\File:
    type: entity
    table: null
    repositoryClass: Lantern\FileMgrBundle\Entity\FileRepository
    fields:
        id:
            type: integer
            id:   true
            generator:
                strategy: AUTO
        filename:
            type:   string
            length: 255
        realpath:
            type: string
            length: 255
        relativePath:
            type: string
            length: 255
        relativePathname:
            type: string
            length: 255
        size:
            type: integer
        type:
            type: string
            length: '16'
        mimetype:
            type: string
            length: '16'
        chmod:
            type: string
            length: '4'
        chown:
            type: string
            length: '16'
        chgrp:
            type: string
            length: '16'
        createdDatetime:
            type: datetime
        modifiedDatetime:
            type: datetime
        lastAccessedDatetime:
            type: datetime
        hash:
            type: string
            length: 255
    lifecycleCallbacks: {  }
