Lantern\FileMgrBundle\Entity\File:
    type:            entity
    table:           lantern_file
    repositoryClass: Lantern\FileMgrBundle\Entity\FileRepository
    id:
        id:
            id:       true
            type:     integer
            unsigned: false
            nullable: false
            generator:
                strategy: AUTO
            sequenceGenerator:
                sequenceName:   lantern_file_id_seq
                initialValue:   1
                allocationSize: 1
    fields:
        filename:
            column:   filename
            type:     string
            length:   255
            nullable: true
            unique:   false
        realPath:
            column:   real_path
            type:     string
            length:   255
            nullable: true
            unique:   false
        relativePath:
            column:   relative_path
            type:     string
            length:   255
            nullable: true
            unique:   false
        relativePathName:
            column:   relative_path_name
            type:     string
            length:   255
            nullable: true
            unique:   false
        size:
            column:   size
            type:     integer
            nullable: true
            unique:   false
        type:
            column:   type
            type:     string
            length:   16
            nullable: true
            unique:   false
        mimeType:
            column:   mime_type
            type:     string
            length:   16
            nullable: true
            unique:   false
        chmod:
            column:   chmod
            type:     string
            length:   4
            nullable: true
            unique:   false
        chown:
            column:   chown
            type:     string
            length:   16
            nullable: true
            unique:   false
        chgrp:
            column:   chgrp
            type:     string
            length:   16
            nullable: true
            unique:   false
        createdDatetime:
            column:   created_datetime
            type:     datetime
            nullable: true
            unique:   false
        modifiedDatetime:
            column:   modified_datetime
            type:     datetime
            nullable: true
            unique:   false
        lastAccessedDatetime:
            column:   last_accessed_datetime
            type:     datetime
            nullable: true
            unique:   false
        hash:
            column:   hash
            type:     string
            length:   255
            nullable: false
    uniqueConstraints:
        lantern_file_hash_unique_idx:
            columns: [ hash ]
    lifecycleCallbacks: {  }
