Lantern\MediaBundle\Entity\Collection:
    type:            entity
    table:           lantern_collection
    repositoryClass: Lantern\MediaBundle\Entity\CollectionRepository
    id:
        id:
            id:       true
            type:     integer
            unsigned: false
            nullable: false
            generator:
                strategy: AUTO
            sequenceGenerator:
                sequenceName:   lantern_collection_id_seq
                initialValue:   1
                allocationSize: 1
    fields:
        title:
            type:      string
            column:    title
            length:    255
            nullable:  false
            unique:    false
        summary:
            type:      text
            column:    summary
            nullable:  true
            unique:    false
        description:
            type:      text
            column:    description
            nullable:  true
            unique:    false
        collectionType:
            type:      string
            column:    collection_type
            length:    255
            nullable:  false
            unique:    false
        startDate:
            type:      datetime
            column:    start_date
            nullable:  true
            unique:    false
        stopDate:
            type:      datetime
            column:    stop_date
            nullable:  true
            unique:    false
        avgRating:
            type:      float
            column:    avg_rating
            scale:     0
            precision: 2
            nullable:  true
            unique:    false
            options:
                comment: "Ratings are stored with decimals but are translated besed on system/user locale settings."
        childOrder:
            type:      integer
            column:    child_order
            nullable:  true
            unique:    false
        locale:
            type:      string
            column:    locale
            length:    16
            nullable:  true
            unique:    false
        createdAt:
            type:      datetime
            column:    created_at
            nullable:  false
            unique:    false
        updatedAt:
            type:      datetime
            column:    updated_at
            nullable:  true
            unique:    false
        attributes:
            type:      json_array
            column:    attributes
            nullable:  true
            unique:    false
    #uniqueConstraints:
    #    lantern_collection_TBD_unique_idx:
    #        columns: [ TBD ]
    oneToMany:
        children:
            targetEntity: Collection
            mappedBy:     parent
        media:
            targetEntity: MediaCollection
            mappedBy:     collection
        tag:
            targetEntity: CollectionTag
            mappedBy:     collection
    manyToOne:
        parent:
            targetEntity: Collection
            inversedBy:   children
            joinColumn:
                name:                 parent
                referencedColumnName: id
        createdBy:
            targetEntity: Lantern\MediaBundle\Model\UserSubjectInterface
            joinColumn:
                name:                 created_by
                referencedColumnName: id
        updatedBy:
            targetEntity: Lantern\MediaBundle\Model\UserSubjectInterface
            joinColumn:
                name:                 updated_by
                referencedColumnName: id
    lifecycleCallbacks: {  }
