Lantern\MediaBundle\Entity\Tag:
    type:            entity
    table:           lantern_tag
    repositoryClass: Lantern\MediaBundle\Entity\TagRepository
    id:
        id:
            id:       true
            type:     integer
            unsigned: false
            nullable: false
            generator:
                strategy: AUTO
            sequenceGenerator:
                sequenceName:   lantern_tag_id_seq
                initialValue:   1
                allocationSize: 1
    fields:
        shortName:
            type:     string
            column:   short_name
            length:   16
            nullable: false
            unique:   false
        longName:
            type:     text
            column:   long_name
            length:   64
            nullable: true
            unique:   false
        description:
            type:     text
            column:   description
            nullable: true
            unique:   false
        locale:
            type:     string
            column:   locale
            length:   16
            length:   true
            unique:   false
        displayType:
            type:     string
            column:   display_type
            length:   16
            nullable: true
            unique:   false
        display:
            type:     text
            column:   display
            nullable: true
            unique:   false
        isEditable:
            type:     boolean
            column:   is_editable
            nullable: true
            unique:   false
        createdAt:
            type:     datetime
            column:   created_at
            nullable: false
            unique:   false
        updatedAt:
            type:     datetime
            column:   updated_at
            nullable: true
            unique:   false
    uniqueConstraints:
        lantern_tag_short_name_locale_unique_idx:
            columns: [ short_name, locale ]
    oneToMany:
        tagTagA:
            targetEntity: TagTag
            mappedBy:     tagA
        tagTagZ:
            targetEntity: TagTag
            mappedBy:     tagZ
        media:
            targetEntity: MediaTag
            mappedBy:     tag
        collection:
            targetEntity: CollectionTag
            mappedBy:     tag
    manyToOne:
        createdBy:
            targetEntity: Lantern\MediaBundle\Model\UserSubjectInterface
            joinColumn:
                name:                 created_by
                referencedColumnName: id
        updatedBy:
            targetEntity: Lantern\MediaBundle\Model\UserSubjectInterface
            joinColumn:
                name:                 updated_by
                referencedColumnName: id
    lifecycleCallbacks: {  }
