Lantern\MenuBundle\Entity\Item:
    type:            entity
    table:           lantern_item
    repositoryClass: Lantern\MenuBundle\Entity\ItemRepository
    id:
        id:
            id:       true
            type:     integer
            unsigned: false
            nullable: false
            generator:
                strategy: AUTO
            sequenceGenerator:
                sequenceName:   lantern_item_id_seq
                initialValue:   1
                allocationSize: 1
    fields:
        shortName:
            column:   short_name
            type:     string
            length:   16
            nullable: false
        longName:
            column:   long_name
            type:     string
            length:   64
            nullable: true
            unique:   false
        description:
            column:   description
            type:     text
            nullable: true
            unique:   false
        display:
            column:   display
            type:     text
            nullable: true
            unique:   false
        route:
            column:   route
            type:     string
            length:   255
            nullable: false
            unique:   false
        parameters:
            column:   parameters
            type:     string
            length:   255
            nullable: true
            unique:   false
        #parent:
        #children:
    uniqueConstraints:
        lantern_item_unique_idx:
            columns: [ short_name ]
    lifecycleCallbacks: {  }
