Lantern\AuthBundle\Entity\Group:
    type:            entity
    table:           lantern_group
    repositoryClass: Lantern\AuthBundle\Entity\GroupRepository
    id:
        id:
            id:       true
            type:     integer
            unsigned: false
            nullable: false
            generator:
                strategy: AUTO
            sequenceGenerator:
                sequenceName:   lantern_group_id_seq
                initialValue:   1
                allocationSize: 1
    fields:
        shortName:
            column:   short_name
            type:     string
            length:   32
            nullable: false
        longName:
            column:   long_name
            type:     string
            length:   64
            nullable: true
            unique:   false
        description:
            column:   description
            type:     text
            nullable: true
            unique:   false
        isActive:
            column:   is_active
            type:     boolean
            nullable: true
            unique:   false
    uniqueConstraints:
        lantern_group_short_name_unique_idx:
            columns: [ short_name ]
    manyToMany:
        roles:
            targetEntity: Role
            inversedBy:   groups
            joinTable:
                name: lantern_group_roles
                joinColumns:
                    group_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    role_id:
                        referencedColumnName: id
        users:
            targetEntity: User
            mappedBy:     groups
    oneToMany:
        children:
            targetEntity: Group
            mappedBy:     parent
    manyToOne:
        parent:
            targetEntity: Group
            inversedBy:   children
    lifecycleCallbacks: {  }