Lantern\AuthBundle\Entity\Role:
    type:            entity
    table:           lantern_role
    repositoryClass: Lantern\AuthBundle\Entity\RoleRepository
    id:
        id:
            id:       true
            type:     integer
            unsigned: false
            nullable: false
            generator:
                strategy: AUTO
            sequenceGenerator:
                sequenceName:   lantern_role_id_seq
                initialValue:   1
                allocationSize: 1
    fields:
        shortName:
            column:   short_name
            type:     string
            length:   32
            nullable: false
        longName:
            column:   long_name
            type:     string
            length:   64
            nullable: true
            unique:   false
        description:
            column:   description
            type:     text
            nullable: true
            unique:   false
        isActive:
            column:   is_active
            type:     boolean
            nullable: true
            unique:   false
    uniqueConstraints:
        lantern_role_short_name_unique_idx:
            columns: [ short_name ]
    oneToMany:
        children:
            targetEntity: Role
            mappedBy:     parent
    manyToOne:
        parent:
            targetEntity: Role
            inversedBy:   children
    manyToMany:
        users:
            targetEntity: User
            mappedBy:     userRoles
        groups:
            targetEntity: Group
            mappedBy:     roles
    lifecycleCallbacks: {  }