Lantern\AuthBundle\Entity\User:
    type:            entity
    table:           lantern_user
    repositoryClass: Lantern\AuthBundle\Entity\UserRepository
    id:
        id:
            id:       true
            type:     integer
            unsigned: false
            nullable: false
            generator:
                strategy: AUTO
            sequenceGenerator:
                sequenceName:   lantern_user_id_seq
                initialValue:   1
                allocationSize: 1
    fields:
        username:
            column:   username
            type:     string
            length:   64
            nullable: false
        firstName:
            column:   first_name
            type:     string
            length:   64
            nullable: true
            unique:   false
        lastName:
            column:   last_name
            type:     string
            length:   64
            nullable: true
            unique:   false
        nickname:
            column:   nickname
            type:     string
            length:   64
            nullable: true
            unique:   false
        password:
            column:   password
            type:     string
            length:   64
            nullable: false
            unique:   false
        salt:
            column:   salt
            type:     string
            length:   32
            nullable: false
            unique:   false
        email:
            column:   email
            type:     string
            length:   64
            nullable: false
        lastLogin:
            column:   last_login
            type:     datetime
            nullable: true
            unique:   false
        isActive:
            column:   is_active
            type:     boolean
            nullable: true
            unique:   false
        isLocked:
            column:   is_locked
            type:     boolean
            nullable: true
            unique:   false
    uniqueConstraints:
        lantern_user_username_unique_idx:
            columns: [ username ]
        lantern_user_email_unique_idx:
            columns: [ email ]
    manyToMany:
        groups:
            targetEntity: Group
            inversedBy:   users
            joinTable:
                name: lantern_user_group
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    group_id:
                        referencedColumnName: id
        userRoles:
            targetEntity: Role
            inversedBy:   users
            joinTable:
                name: lantern_user_role
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    role_id:
                        referencedColumnName: id

    lifecycleCallbacks: {  }
