parameters:
#    lantern_intl.example.class: Lantern\IntlBundle\Example

services:
#    lantern_intl.example:
#        class: %lantern_intl.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
