parameters:
#    lantern_admin.example.class: Lantern\AdminBundle\Example

services:
#    lantern_admin.example:
#        class: %lantern_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
