parameters:
#    lantern_twig_ext.example.class: Lantern\TwigExtBundle\Example

services:
#    lantern_twig_ext.example:
#        class: %lantern_twig_ext.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
