<?php

namespace Lantern\MenuBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Item Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends EntityRepository
{
}
