LanternAuthBundle_index:
    pattern:  /
    defaults: { _controller: LanternAuthBundle:Default:index }

LanternAuthBundle_user:
    resource: "@LanternAuthBundle/Resources/config/routing/user.yml"
    prefix:   /admin/user

LanternAuthBundle_group:
    resource: "@LanternAuthBundle/Resources/config/routing/group.yml"
    prefix:   /admin/group

LanternAuthBundle_role:
    resource: "@LanternAuthBundle/Resources/config/routing/role.yml"
    prefix:   /admin/role