parameters:
    lantern_auth.role_manager.class: Lantern\AuthBundle\Entity\RoleManager

services:
    lantern_auth.role_manager:
        class:     %lantern_auth.role_manager.class%
        arguments: [ @security.role_hierarchy ]