parameters:
#    lantern_auth.example.class: Lantern\AuthBundle\Example

services:
#    lantern_auth.example:
#        class: %lantern_auth.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
