LanternAuthBundle_group_index:
    pattern:  /
    defaults: { _controller: "LanternAuthBundle:Group:index" }

LanternAuthBundle_group_view:
    pattern:  /{id}/view
    defaults: { _controller: "LanternAuthBundle:Group:view" }

LanternAuthBundle_group_new:
    pattern:  /new
    defaults: { _controller: "LanternAuthBundle:Group:new" }

LanternAuthBundle_group_create:
    pattern:  /create
    defaults: { _controller: "LanternAuthBundle:Group:create" }
    requirements: { _method: post }

LanternAuthBundle_group_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "LanternAuthBundle:Group:edit" }

LanternAuthBundle_group_update:
    pattern:  /{id}/update
    defaults: { _controller: "LanternAuthBundle:Group:update" }
    requirements: { _method: post|put }

LanternAuthBundle_group_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "LanternAuthBundle:Group:delete" }
    requirements: { _method: post|delete }
