LanternAuthBundle_role_index:
    pattern:  /
    defaults: { _controller: "LanternAuthBundle:Role:index" }

LanternAuthBundle_role_view:
    pattern:  /{id}/view
    defaults: { _controller: "LanternAuthBundle:Role:view" }

LanternAuthBundle_role_new:
    pattern:  /new
    defaults: { _controller: "LanternAuthBundle:Role:new" }

LanternAuthBundle_role_create:
    pattern:  /create
    defaults: { _controller: "LanternAuthBundle:Role:create" }
    requirements: { _method: post }

LanternAuthBundle_role_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "LanternAuthBundle:Role:edit" }

LanternAuthBundle_role_update:
    pattern:  /{id}/update
    defaults: { _controller: "LanternAuthBundle:Role:update" }
    requirements: { _method: post|put }

LanternAuthBundle_role_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "LanternAuthBundle:Role:delete" }
    requirements: { _method: post|delete }
