LanternAuthBundle_user_index:
    pattern:  /
    defaults: { _controller: "LanternAuthBundle:User:index" }

LanternAuthBundle_user_view:
    pattern:  /{id}/view
    defaults: { _controller: "LanternAuthBundle:User:view" }

LanternAuthBundle_user_new:
    pattern:  /new
    defaults: { _controller: "LanternAuthBundle:User:new" }

LanternAuthBundle_user_create:
    pattern:  /create
    defaults: { _controller: "LanternAuthBundle:User:create" }
    requirements: { _method: post }

LanternAuthBundle_user_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "LanternAuthBundle:User:edit" }

LanternAuthBundle_user_update:
    pattern:  /{id}/update
    defaults: { _controller: "LanternAuthBundle:User:update" }
    requirements: { _method: post|put }

LanternAuthBundle_user_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "LanternAuthBundle:User:delete" }
    requirements: { _method: post|delete }
