parameters:
#    lantern_user.example.class: Lantern\UserBundle\Example

services:
#    lantern_user.example:
#        class: %lantern_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
