lantern_file_mgr_homepage:
    pattern:  /
    defaults: { _controller: LanternFileMgrBundle:Default:index }

get_dir:
    path:     /getdir
    defaults: { _controller: LanternFileMgrBundle:Default:getDir }

#get_dir:
#    path:     /{dir}
#    defaults: { _controller: LanternFileMgrBundle:Default:getDir }
#    requirements:
#        name: ".+"
