parameters:
#    lantern_file_mgr.example.class: Lantern\FileMgrBundle\Example

services:
#    lantern_file_mgr.example:
#        class: %lantern_file_mgr.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
